# Base Node Alpine
FROM node:24.3-alpine

WORKDIR /app

# Copiar package.json e instalar dependências
COPY package*.json ./
RUN npm install

# Copiar todo o projeto
COPY . .

# Limpar e compilar TypeScript da API
RUN npm run clearapi:unix && npm run build:api:unix

# Definir porta
EXPOSE 3002

# Rodar API no container
CMD ["node", "api/dist/server.js"]
